### ISSUE TITLE
deserializeArray issue

### ISSUE THREAD

**Issue by marctanguy** [shakilsiraj/json-object-mapper#24]
Hello !

I have a problem when I want to deserialize an array. Here is my code:
`@JsonProperty({name: 'myArray', required: false, type: Array<models.myVar>()})
public myArray: Array<models.myVar> = undefined;`

This thrown an error like this when I use the ObjectMapper.deserialize method:

> TypeError:  metadata.type is not a constructor
> 	    at http://localhost:9876/_karma_webpack_/webpack:/D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:303:1
> 	    at Array.forEach (<anonymous>)
> 	    at Object.DeserializeComplexType D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:265:1)
> 	    at runDeserialization D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:612:1)
> 	    at Object.webpackJsonp.../../../../json-object-mapper/dist/ObjectMapper.es2015.js.ObjectMapper.deserialize 

I've first modify my code like this:
`  
@JsonProperty({name: 'myArray', required: false, type: Array<models.myVar>()})
  public myArray: models.myVar[] = undefined;
`

But I've this other error:
> TypeError: type is not a constructor
> 	    at Object.DeserializeArrayType D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:222:1)
> 	    at http://localhost:9876/_karma_webpack_/webpack:/D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:316:1
> 	    at Array.forEach (<anonymous>)
> 	    at Object.DeserializeComplexType D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:265:1)
> 	    at runDeserialization D:/projets/.../node_modules/json-object-mapper/dist/ObjectMapper.es2015.js:612:1)
> 	    at Object.webpackJsonp.../../../../json-object-mapper/dist/ObjectMapper.es2015.js.ObjectMapper.deserialize

I then modified the DeserializeArrayType method like this:
`var typeInstance = new type();` to `var typeInstance = type;`

And it works now...

Can you tell me if there is a mistake in my or your code ? :)

Thanks a lot !

Marc

**Comment by marctanguy** [comment]
My bad ....

`@JsonProperty({name: 'myArray', required: false, type: models.myVar}) 
public myArray: models.myVar[] = undefined;`

works like a charm ...
